spring.application.name=trade
server.port=6004
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://stock-market-database.mysql.database.azure.com/stock-market-database
spring.datasource.username=stock_market_user
spring.datasource.password=L83mczECWgDU9BZ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect