spring.application.name=shares-brokering
server.port=6001
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/stock-market-database
spring.datasource.username=root
spring.datasource.password=dummypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
